package:
  name: microscopes-mixturemodel
  version: "0.1.0"

source:
  git_url: https://github.com/datamicroscopes/mixturemodel.git

requirements:
  build:
    - cmake
    - python
    - numpy ==1.8.2
    - cython >=0.20.2
    - distributions >=2.0.23
    - libprotobuf
    - eigen3
    - microscopes-common
    - microscopes-kernels
  run:
    - python
    - numpy ==1.8.2
    - scipy
    - distributions >=2.0.23
    - libprotobuf
    - protobuf
    - microscopes-common
    - microscopes-kernels

test:
  imports:
    - microscopes.mixture
    - microscopes.mixture.definition
    - microscopes.mixture.model

about:
  home: https://github.com/datamicroscopes/mixturemodel
